from app import db

db.drop_all()
db.create_all()


conn  = db.engine

conn.execute("insert into csec values('Mathematics');")
conn.execute("insert into csec values('Additional Mathematics');")
conn.execute("insert into csec values('Biology');")
conn.execute("insert into csec values('Chemistry');")
conn.execute("insert into csec values('Physics');")
conn.execute("insert into csec values('Technical Drawing');")
conn.execute("insert into csec values('French');")
conn.execute("insert into csec values('Spanish');")
conn.execute("insert into csec values('Art');")
conn.execute("insert into csec values('Agricultural Science');")
conn.execute("insert into csec values('Building Technology');")
conn.execute("insert into csec values('Caribbean History');")
conn.execute("insert into csec values('Clothing and Textiles');")
conn.execute("insert into csec values('English Language');")
conn.execute("insert into csec values('English Literature');")
conn.execute("insert into csec values('Food and Nutrition');")
conn.execute("insert into csec values('Geography');")
conn.execute("insert into csec values('Home Economics Management');")
conn.execute("insert into csec values('Human and Social Biology');")
conn.execute("insert into csec values('Music');")
conn.execute("insert into csec values('Religious Education');")
conn.execute("insert into csec values('Theatre Arts');")
conn.execute("insert into csec values('Visual Arts');")
conn.execute("insert into csec values('Principles of Accounts');")
conn.execute("insert into csec values('Economics');")


conn.execute("insert into cape (\"subjectName\",\"capacity\") values ('Accounting',30);")
conn.execute("insert into cape (\"subjectName\",\"capacity\") values ('Agricultural Science',30);")
conn.execute("insert into cape (\"subjectName\",\"capacity\") values ('Applied Mathematics',30);")
conn.execute("insert into cape (\"subjectName\",\"capacity\") values ('Art And Design',30);")
conn.execute("insert into cape (\"subjectName\",\"capacity\") values ('Biology',30);")
conn.execute("insert into cape (\"subjectName\",\"capacity\") values ('Building And Mechanical Engineering Drawing',30);")
conn.execute("insert into cape (\"subjectName\",\"capacity\") values ('Caribbean Studies',30);")
conn.execute("insert into cape (\"subjectName\",\"capacity\") values ('Chemistry',30);")
conn.execute("insert into cape (\"subjectName\",\"capacity\") values ('Communication Studies',30);")
conn.execute("insert into cape (\"subjectName\",\"capacity\") values ('Computer Science',30);")
conn.execute("insert into cape (\"subjectName\",\"capacity\") values ('Digital Media',30);")
conn.execute("insert into cape (\"subjectName\",\"capacity\") values ('Electrical And Electronic Engineering Technology',30);")
conn.execute("insert into cape (\"subjectName\",\"capacity\") values ('Economics',30);")
conn.execute("insert into cape (\"subjectName\",\"capacity\") values ('Entrepreneurship',30);")
conn.execute("insert into cape (\"subjectName\",\"capacity\") values ('Environmental Science',30);")
conn.execute("insert into cape (\"subjectName\",\"capacity\") values ('Financial Services Studies',30);")
conn.execute("insert into cape (\"subjectName\",\"capacity\") values ('Food And Nutrition',30);")
conn.execute("insert into cape (\"subjectName\",\"capacity\") values ('French',30);")
conn.execute("insert into cape (\"subjectName\",\"capacity\") values ('Geography',30);")
conn.execute("insert into cape (\"subjectName\",\"capacity\") values ('Green Engineering',30);")
conn.execute("insert into cape (\"subjectName\",\"capacity\") values ('History',30);")
conn.execute("insert into cape (\"subjectName\",\"capacity\") values ('Information Technology',30);")
conn.execute("insert into cape (\"subjectName\",\"capacity\") values ('Integrated Mathematics',30);")
conn.execute("insert into cape (\"subjectName\",\"capacity\") values ('Law',30);")
conn.execute("insert into cape (\"subjectName\",\"capacity\") values ('Literatures In English',30);")
conn.execute("insert into cape (\"subjectName\",\"capacity\") values ('Logistics And Supply Chain Operations',30);")
conn.execute("insert into cape (\"subjectName\",\"capacity\") values ('Management Of Business',30);")
conn.execute("insert into cape (\"subjectName\",\"capacity\") values ('Performing Arts',30);")
conn.execute("insert into cape (\"subjectName\",\"capacity\") values ('Physics',30);")
conn.execute("insert into cape (\"subjectName\",\"capacity\") values ('Physical Education And Sport',30);")
conn.execute("insert into cape (\"subjectName\",\"capacity\") values ('Pure Mathematics',30);")
conn.execute("insert into cape (\"subjectName\",\"capacity\") values ('Sociology',30);")
conn.execute("insert into cape (\"subjectName\",\"capacity\") values ('Spanish',30);")
conn.execute("insert into cape (\"subjectName\",\"capacity\") values ('Tourism',30);")



