"""empty message

Revision ID: 2b98639b73c4
Revises: 
Create Date: 2017-03-14 00:02:15.296924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b98639b73c4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cape',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subjectName', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('csec',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subjectName', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student',
    sa.Column('studentID', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=50), nullable=True),
    sa.Column('authenticated', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('studentID')
    )
    op.create_table('application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studentID', sa.String(length=50), nullable=True),
    sa.Column('subjectID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['studentID'], ['student.studentID'], ),
    sa.ForeignKeyConstraint(['subjectID'], ['cape.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('studied',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studentID', sa.String(length=50), nullable=True),
    sa.Column('grade', sa.String(length=5), nullable=True),
    sa.Column('subjectID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['studentID'], ['student.studentID'], ),
    sa.ForeignKeyConstraint(['subjectID'], ['csec.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('studied')
    op.drop_table('application')
    op.drop_table('student')
    op.drop_table('csec')
    op.drop_table('cape')
    # ### end Alembic commands ###
