"""empty message

Revision ID: a28fc76bd584
Revises: 2b98639b73c4
Create Date: 2017-03-21 12:52:31.506553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a28fc76bd584'
down_revision = '2b98639b73c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('csec',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subjectName', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subjectName')
    )
    op.create_foreign_key(None, 'studied', 'csec', ['subjectID'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'studied', type_='foreignkey')
    op.drop_table('csec')
    # ### end Alembic commands ###
