"""empty message

Revision ID: e0d4d31825cd
Revises: f0435c695ed7
Create Date: 2017-04-20 17:25:42.127297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0d4d31825cd'
down_revision = 'f0435c695ed7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cape', sa.Column('capacity', sa.Integer(), nullable=True))
    op.add_column('cape', sa.Column('prequisiteSubject', sa.String(length=80), nullable=True))
    op.create_foreign_key(None, 'cape', 'csec', ['prequisiteSubject'], ['subjectName'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cape', type_='foreignkey')
    op.drop_column('cape', 'prequisiteSubject')
    op.drop_column('cape', 'capacity')
    # ### end Alembic commands ###
